import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { cookies } from "next/headers"
import { Toaster } from "@/components/ui/toaster"
import { SidebarProvider, SidebarInset } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import NavBar from "@/components/navbar"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "mnms",
  description: "Generated by create next app",
};

export  default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies()
  const defaultOpen = cookieStore.get("sidebar:state")?.value === "true"

  return (

      <SidebarProvider defaultOpen={defaultOpen}>
      <AppSidebar />
      <SidebarInset>

        <div className="flex flex-1 flex-col gap-2 mb-2 mr-2 ml-1 mt-2">
          <NavBar/>
          <div className=" min-h-[100vh] flex-1 rounded-xl bg-muted md:min-h-min p-4" >
            {children}
            <Toaster/>
          </div>
        </div>
      </SidebarInset>
    </SidebarProvider>
  );
}
